---
- name: get ImageStreamTags
  command: oc get imagestreamtags -o "jsonpath={.items[*].metadata.name}"
  register: _is_name
  retries: 600
  delay: 1

- name: create ImageStreamTags list
  set_fact:
    is_data:
      imagestreamtags:
        - name: "{{ zuul.project.short_name }}"
          imagestream: "{{ _is_name.stdout }}"

- name: store ImageStreamTags list in work_root
  copy:
    content: "{{ is_data | to_yaml }}"
    dest: "{{ zuul.executor.work_root }}/imagestreamtags.yaml"
